
[package]
name = "rust-md"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.98"
axum = { version = "0.8.4", features = ["macros"] }
pulldown-cmark = "0.13.0"
notify = { version = "8.0.0", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml_ng = "0.10.0"
tokio = { version = "1.44.2", features = ["full"] }
tower-http = { version = "0.6.1", features = ["trace", "cors"] }
colored = "3"
