
[package]
name = "rust-md"
version = "0.1.0"
edition = "2021"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.97"
axum = { version = "0.8.1", features = ["macros"]}
dotenvy = "0.15.7"
markdown = "1.0.0-alpha.23"
mdast_util_to_markdown = "0.0.1"
regex = "1.11.1"
scraper = "0.23.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml_ng = "0.10.0"
tokio = { version = "1.44.1", features = ["full"] }
tower-http = { version = "0.6.1", features = ["trace", "cors"] }

